spring:
  profiles:
    active: local
  main:
    log-startup-info: true
  jackson:
    serialization:
      indent-output: true
    time-zone:
      Asia/Ho_Chi_Minh  
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://10.1.43.201:3306/vti_academy
    username: root
    password: Student1234
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
     
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: MYSQL
    show-sql: true
    open-in-view: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  http:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
server:
  context-path: /VTI_Academy_Web
  port: 8080
security:
  basic:
    enabled: false
---
spring:
  profiles: product
  datasource:
    url: jdbc:postgresql:xxx
    username: vti_prd
    password: vtipassword
    driverClassName: org.postgresql.Driver
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
     
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: false
    open-in-view: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  http:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
server:
  context-path: /VTI_Academy_Web
  port: 8080
security:
  basic:
    enabled: false
  oauth2:
    resource:
      filter-order: 3
